---

base_locale: en
locales: [en]

data:
  external:
    - "<%= %x[bundle info decidim-core --path].chomp %>/config/locales/%{locale}.yml"

ignore_unused:
  - decidim.community_templates.admin.menu.community_templates

ignore_missing:
