---

base_locale: en
locales: [en]

data:
  external:
    - "<%= %x[bundle info decidim-core --path].chomp %>/config/locales/%{locale}.yml"

ignore_unused:
  - decidim.community_templates.admin.menu.*
  - activemodel.errors.models.template.attributes.participatory_space.unsupported
  - activerecord.errors.models.decidim/community_templates/community_template.attributes.*

ignore_missing:
