---

base_locale: en
locales: [en]

data:
  external:
    - "<%= %x[bundle info decidim-core --path].chomp %>/config/locales/%{locale}.yml"

ignore_unused:
  - decidim.community_templates.admin.menu.*
  # FIXME: includes cells
  - decidim.community_templates.admin.template_create.*
  - decidim.community_templates.admin.template_update.*
  - decidim.community_templates.admin.template_form.*
  - activemodel.errors.models.template.attributes.participatory_space.unsupported
  - activemodel.errors.models.decidim/community_templates/catalog.attributes.*
  - activerecord.errors.models.decidim/community_templates/template_use.attributes.*
  - activerecord.errors.models.decidim/community_templates/template_source.attributes.*
  - activemodel.errors.models.decidim/community_templates/template.attributes.*
  - decidim.community_templates.admin.direct_link_modal.*

ignore_missing:
