name: "[CI] Lint"

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  CI: "true"
  RUBY_VERSION: 3.3.4
  NODE_VERSION: 22.14.0
  SHAKAPACKER_RUNTIME_COMPILE: "false"

jobs:
  lint-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # - run: npm ci
      #   name: Install JS deps

      # - run: npm run lint
      #   name: Lint JS files

      # - run: npm run stylelint
      #   name: Lint SCSS files

      - run: bundle exec rubocop -P
        name: Lint Ruby files

      # - run: bundle exec erb_lint app/**/*.erb
      #   name: Lint ERB files
